// Firefox exposes the promise-based `browser` namespace. Fall back to `chrome`
// so the rest of this file mirrors the Chromium build one-to-one.
const browser = globalThis.browser ?? globalThis.chrome;

/**
 * Popup script for FinTube Cookie Exporter.
 *
 * FinTube has no desktop app to deep-link into - it runs inside Jellyfin. So
 * this popup does one job: read the YouTube cookies from your browser, format
 * them as a Netscape cookie file (what yt-dlp expects), and let you copy them
 * for pasting into FinTube's plugin settings.
 */

// FinTube only downloads from YouTube, so that's all we export cookies for.
const SUPPORTED_DOMAINS = ["youtube.com", "youtu.be"];

// Cookies are read from these domains. youtube.com holds the login/age cookies;
// google.com holds the consent/SOCS cookie yt-dlp sometimes needs too.
const COOKIE_DOMAINS = ["youtube.com", "google.com"];

const t = (key) => browser.i18n.getMessage(key) || key;

function isSupportedUrl(url) {
  if (!url) return false;
  try {
    const host = new URL(url).hostname;
    return SUPPORTED_DOMAINS.some((d) => host === d || host.endsWith("." + d));
  } catch {
    return false;
  }
}

function toNetscapeLine(c) {
  // The include-subdomains flag (field 2) MUST agree with whether the domain
  // (field 1) starts with a dot, otherwise http.cookiejar - used by yt-dlp -
  // raises an AssertionError ("http.cookiejar bug!") and rejects the whole
  // file. Keep the domain exactly as the browser reports it and derive the flag
  // from it so the two can never disagree.
  const flag = c.domain.startsWith(".") ? "TRUE" : "FALSE";
  const secure = c.secure ? "TRUE" : "FALSE";
  const expiry = c.expirationDate ? Math.floor(c.expirationDate) : 0;
  return `${c.domain}\t${flag}\t${c.path}\t${secure}\t${expiry}\t${c.name}\t${c.value}`;
}

/** Collect cookies for every relevant domain and render a Netscape cookie file. */
async function getCookieText() {
  const seen = new Set();
  const lines = [];

  for (const domain of COOKIE_DOMAINS) {
    const cookies = await browser.cookies.getAll({ domain });
    for (const c of cookies) {
      // A cookie is uniquely identified by name + domain + path.
      const key = `${c.name}\t${c.domain}\t${c.path}`;
      if (seen.has(key)) continue;
      seen.add(key);
      lines.push(toNetscapeLine(c));
    }
  }

  if (!lines.length) return "";
  const header =
    "# Netscape HTTP Cookie File\n" +
    "# Generated by the FinTube browser extension\n\n";
  return header + lines.join("\n") + "\n";
}

/** Hydrate every [data-i18n] / [data-i18n-placeholder] node. */
function applyI18n() {
  document.querySelectorAll("[data-i18n]").forEach((el) => {
    const msg = t(el.getAttribute("data-i18n"));
    if (msg) el.textContent = msg;
  });
  document.querySelectorAll("[data-i18n-placeholder]").forEach((el) => {
    const msg = t(el.getAttribute("data-i18n-placeholder"));
    if (msg) el.setAttribute("placeholder", msg);
  });
}

function setStatus(kind, key) {
  const el = document.getElementById("status");
  const text = document.getElementById("status-text");
  el.classList.remove("pill-ok", "pill-bad", "pill-muted");
  el.classList.add(
    kind === "ok" ? "pill-ok" : kind === "bad" ? "pill-bad" : "pill-muted"
  );
  text.textContent = t(key);
}

document.addEventListener("DOMContentLoaded", async () => {
  applyI18n();

  const copyBtn = document.getElementById("copy-btn");
  const btnText = document.getElementById("btn-text");
  const cookieBox = document.getElementById("cookie-box");
  const emptyHint = document.getElementById("empty-hint");

  const [tab] = await browser.tabs.query({ active: true, currentWindow: true });
  const onYouTube = isSupportedUrl(tab?.url || "");

  // We can export YouTube cookies whether or not the user is currently on a
  // YouTube tab - the status pill just tells them what's going on.
  setStatus(onYouTube ? "ok" : "muted", onYouTube ? "popupSupported" : "popupNotYouTube");

  const cookieText = await getCookieText();

  if (!cookieText) {
    cookieBox.value = "";
    emptyHint.hidden = false;
    copyBtn.disabled = true;
    return;
  }

  cookieBox.value = cookieText;
  copyBtn.disabled = false;

  copyBtn.addEventListener("click", async () => {
    try {
      await navigator.clipboard.writeText(cookieText);
    } catch {
      // Clipboard API can be blocked; fall back to selecting the textarea.
      cookieBox.focus();
      cookieBox.select();
      document.execCommand("copy");
    }
    btnText.textContent = t("popupCopied");
    copyBtn.disabled = true;
    setTimeout(() => {
      btnText.textContent = t("popupCopyBtn");
      copyBtn.disabled = false;
    }, 1600);
  });
});
